//
//  quoteList.swift
//  Kanye-Quotes
//
//  Created by James Lea on 5/21/23.
//

import Foundation

let kanyeQuotes = [
    "I feel like I'm too busy writing history to read it.",
    "I am God's vessel. But my greatest pain in life is that I will never be able to see myself perform live.",
    "I liberate minds with my music.",
    "My greatest award is what I'm about to do.",
    "I refuse to accept other people's ideas of happiness for me. As if there's a 'one size fits all' standard for happiness.",
    "I'm like a vessel, and God has chosen me to be the voice and the connector.",
    "I still think I am the greatest.",
    "Believe in your flyness...conquer your shyness.",
    "I will be the leader of a company that ends up being worth billions of dollars because I got the answers. I understand culture. I am the nucleus.",
    "My greatest pain in life is that I will never be able to see myself perform live.",
    "I feel like I'm too busy writing history to read it.",
    "I'm doing pretty good as far as geniuses go.",
    "I'm a creative genius.",
    "I feel like a little bit, like, I'm the Braveheart of creativity.",
    "I'm the closest that hip-hop is getting to God.",
    "I'm living in the future, so the present is my past.",
    "I am Warhol. I am the number one most impactful artist of our generation.",
    "I am so credible and so influential and so relevant that I will change things.",
    "I'm just the vessel through which music flows.",
    "I'm not a businessman; I'm a business, man!",
    "I still think I am the greatest.",
    "Believe in your flyness...conquer your shyness.",
    "I will be the leader of a company that ends up being worth billions of dollars because I got the answers. I understand culture. I am the nucleus.",
    "My greatest pain in life is that I will never be able to see myself perform live.",
    "I feel like I'm too busy writing history to read it.",
    "I'm doing pretty good as far as geniuses go.",
    "I'm a creative genius.",
    "I feel like a little bit, like, I'm the Braveheart of creativity.",
    "I'm the closest that hip-hop is getting to God.",
    "I'm living in the future, so the present is my past.",
    "I am Warhol. I am the number one most impactful artist of our generation.",
    "I am so credible and so influential and so relevant that I will change things.",
    "I'm just the vessel through which music flows.",
    "I'm not a businessman; I'm a business, man!",
    "I'm like a vessel, and God has chosen me to be the voice and the connector.",
    "My greatest award is what I'm about to do.",
    "I refuse to accept other people's ideas of happiness for me. As if there's a 'one size fits all' standard for happiness.",
    "I liberate minds with my music.",
    "I'm like a TV show host: I can't make anything less than what Steve Jobs made, so I can't be relegated as a rapper.",
    "People always say that you can't please everybody. I think that's a cop-out. Why not attempt it? 'Cause think of all the people that you will please if you try.",
    "I'm a pop enigma. I live and breathe every element in life.",
    "I am the number one human being in music. That means any person that's living or breathing is number two.",
    "Keep your nose out the sky, keep your heart to God, and keep your face to the rising sun.",
    "I'm a minimalist in a rapper's body.",
    "If you have the opportunity to play this game of life, you need to appreciate every moment. A lot of people don't appreciate the moment until it's passed.",
    "I'm just giving of my body on the stage and putting my emotions and energies out there.",
    "I have to dress Kim Kardashian every day of my life as a walking work of art.",
    "I have a lot of experience in the fashion industry being next to the most influential person in fashion.",
    "I really appreciate the moments that I was able to win rap album of the year or whatever.",
    "I don't care about having a legacy, I don't care about being remembered.",
    "I am a god. I create art and it's supreme.",
    "The concept of commercialism in the fashion and art world is looked down upon. You know, just to think, 'What amount of creativity does it take to make something that masses of people like?' And, 'How does creativity apply across the board?'",
    "People always say that you can't please everybody. I think that's a cop-out. Why not attempt it? 'Cause think of all the people that you will please if you try.",
    "I hate when I'm on a flight and I wake up with a water bottle next to me like oh great now I gotta be responsible for this water bottle.",
    "I refuse to follow those rules that society has set up in the way that they control people with low self-esteem.",
    "Keep your nose out the sky, keep your heart to God, and keep your face to the rising sun.",
    "I want the world to be better! All I want is positive! All I want is dopeness!",
    "I refuse to follow those rules that society has set up in the way that they control people with low self-esteem.",
    "My greatest pain in life is that I will never be able to see myself perform live.",
    "I'm the most influential person of the past ten years. I am Shakespeare in the flesh.",
    "The media crucify me like they did Christ.",
    "When someone comes up and says something like, 'I am a god,' everybody says, 'Who does he think he is?' I just told you who I thought I was: a god. I just told you. That's who I think I am.",
    "The only luxury is time. The time you get to spend with your family.",
    "I was never really good at anything except for the ability to learn.",
    "You can't look at a glass half full or empty if it's overflowing.",
    "I'll say things that are serious and put them in a joke form so people can enjoy them. We laugh to keep from crying.",
    "I don't care about having a legacy, I don't care about being remembered.",
    "I'll never be picture perfect Beyoncé.",
    "I feel like I'm too busy writing history to read it.",
    "Believe in your flyness...conquer your shyness.",
    "I'm not a businessman; I'm a business, man!",
    "I'm a pop enigma. I live and breathe every element in life.",
    "My greatest pain in life is that I will never be able to see myself perform live.",
    "I'm living in the future, so the present is my past.",
    "I am so credible and so influential and so relevant that I will change things.",
    "I'm just the vessel through which music flows.",
    "Keep your nose out the sky, keep your heart to God, and keep your face to the rising sun.",
    "I'm a minimalist in a rapper's body.",
    "If you have the opportunity to play this game of life, you need to appreciate every moment. A lot of people don't appreciate the moment until it's passed.",
    "I have a lot of experience in the fashion industry being next to the most influential person in fashion.",
    "I don't care about having a legacy, I don't care about being remembered.",
    "The concept of commercialism in the fashion and art world is looked down upon. You know, just to think, 'What amount of creativity does it take to make something that masses of people like?' And, 'How does creativity apply across the board?'",
    "I hate when I'm on a flight and I wake up with a water bottle next to me like oh great now I gotta be responsible for this water bottle.",
    "I refuse to follow those rules that society has set up in the way that they control people with low self-esteem.",
    "I want the world to be better! All I want is positive! All I want is dopeness!",
    "I'm the most influential person of the past ten years. I am Shakespeare in the flesh.",
    "The media crucify me like they did Christ.",
    "When someone comes up and says something like, 'I am a god,' everybody says, 'Who does he think he is?' I just told you who I thought I was: a god. I just told you. That's who I think I am.",
    "The only luxury is time. The time you get to spend with your family.",
    "I was never really good at anything except for the ability to learn.",
    "You can't look at a glass half full or empty if it's overflowing.",
    "I'll say things that are serious and put them in a joke form so people can enjoy them. We laugh to keep from crying.",
    "I don't care about having a legacy, I don't care about being remembered.",
    "I'm not comfortable with comfort.",
    "I refuse to accept other people's ideas of happiness for me. As if there's a 'one size fits all' standard for happiness.",
    "I'm a messenger, and the message is fear.",
    "I still think I am the greatest.",
    "I'm on a mission to change the world, one beat at a time.",
    "I believe in limitless possibilities. I believe in me.",
    "I don't follow trends. I create them.",
    "I'm not afraid to fail. I'm afraid of not trying.",
    "I'm an artist, and my art is my truth.",
    "I'm here to inspire and empower people through my music.",
    "I find beauty in the unconventional and the unexpected.",
    "I'm a dreamer with the audacity to chase my dreams.",
    "I'm not here to fit in. I'm here to stand out.",
    "I'm a student of life, constantly learning and growing.",
    "I'm fueled by passion and driven by purpose.",
    "I see greatness in myself and in others.",
    "I believe in the power of love to change the world.",
    "I'm a creator, bringing something new into existence.",
    "I'm a visionary, painting a picture of a better future.",
    "I'm not afraid to challenge the status quo.",
    "I'm a voice for the voiceless, speaking truth to power.",
    "I'm not defined by my past; I'm inspired by my future.",
    "I'm a bridge between cultures, uniting people through music.",
    "I'm a pioneer, breaking new ground and pushing boundaries.",
    "I'm an innovator, constantly pushing the envelope.",
    "I'm a believer in the impossible, making the possible happen.",
    "I'm not just an artist; I'm a movement.",
    "I'm a rebel with a cause, fighting for what I believe in.",
    "I'm not seeking approval; I'm seeking authenticity.",
    "I'm a voice for the underdog, shining a light on injustice.",
    "I'm not here to be average; I'm here to be extraordinary.",
    "I'm a force of nature, unstoppable in my pursuit of greatness.",
    "I'm a catalyst for change, igniting a revolution of the mind.",
    "I'm a symbol of resilience, turning adversity into triumph."
]

